### ISSUE TITLE
doesnt work anymore

### ISSUE THREAD

**Issue by murderuo** [ssut/py-googletrans#100]
im using already this module but now i cant use. 

i get this error:

Traceback (most recent call last):
  File "C:/Users/ugurokur/Desktop/kişisel bilgilerim/python_uygulama/google_translate/translate_exam.py", line 6, in <module>
    print(trans.translate("selam"))
  File "C:\Program Files\Python36\lib\site-packages\googletrans\client.py", line 172, in translate
    data = self._translate(text, dest, src)
  File "C:\Program Files\Python36\lib\site-packages\googletrans\client.py", line 75, in _translate
    token = self.token_acquirer.do(text)
  File "C:\Program Files\Python36\lib\site-packages\googletrans\gtoken.py", line 180, in do
    self._update()
  File "C:\Program Files\Python36\lib\site-packages\googletrans\gtoken.py", line 59, in _update
    code = unicode(self.RE_TKK.search(r.text).group(1)).replace('var ', '')
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by elieobeid7** [comment]
What doesn't work? I just installed it and it works, I'm using python 3

**Comment by murderuo** [comment]
as you see i get token error. 

its could be cause i use cloud translate ?

**Comment by elieobeid7** [comment]
@murderuo Sorry I never used tokens in this library before, I just installed it yesterday, and I'm using the basic example like this

`word = translator.translate('hello', src='en', dest='ar')`

That works fine, if you have a specific problem related to cloud translations and tokens, you should edit your question's title to say 

"cloud translation doesn't work, I got a token error"

Because right now, the title suggests that the entire library doesn't work anymore, which isn't true.

Anyhow I never used cloud translation, if you need it, you might want to take a look at this library

https://pypi.org/project/google-cloud-translate/

**Comment by murderuo** [comment]
i have already two script. one of this work google cloud translate, other this on this module.

a few months ago i used my translate script and it was working fine. but now same script doesnt work.

i think, i use this script and cloud script same time. that's way it doesnt work

if i run colud script it s working. but this module doesnt.

i checked my env. this module installed on my pc
