### ISSUE TITLE
JSONDecodeError from None Issue Again

### ISSUE THREAD

**Issue by gregknaselcs** [ssut/py-googletrans#158]
![image](https://user-images.githubusercontent.com/50967679/76877253-bd344c80-6838-11ea-96fb-85b5add2a94d.png)

**Comment by gregknaselcs** [comment]
Started happening about an hour ago.

**Comment by flyingvirus** [comment]
I also encountered the same problem...

**Comment by sigvaldm** [comment]
Affects me too. Worked smoothly on Friday, yesterday, and earlier today (Tuesday), but suddenly this started appearing.

**Comment by RaidasGrisk** [comment]
Not sure the root cause, but the error originates in _translate method inside the Translator object.

For example, here is [a get request](https://translate.google.com/translate_a/single?client=t&sl=auto&tl=en&hl=en&dt=at&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&ie=UTF-8&oe=UTF-8&otf=1&ssel=0&tsel=0&tk=851163.672849&q=foo+bar+baz) that is being executed inside _translate method.

Here is the response I'm getting:
> Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?

Something must have been changed regarding the google API. Could be related to the token and TokenAcquirer object, but this is hard to debug without prior knowledge.

**Comment by sigvaldm** [comment]
Yes, this is it @RaidasGrisk. Thank you. A quick workaround for me was to cache my translations.  I'm only going to use my script for a one-off job, and don't need a durable solution. As I develop, I've been running the script repeatedly, with several translation requests each time. Adding this caching functionality to the top of my script makes sure the functions `translate` and `detect` are only called once for each string:

```
from diskcache import Cache

cache = Cache('cache')
translator = Translator()

@cache.memoize(tag='translate')
def translate(*args, **kwargs):
    return translator.translate(*args, **kwargs)

@cache.memoize(tag='detect')
def detect(*args, **kwargs):
    return translator.detect(*args, **kwargs)
```

Having implemented this, I simply tried again from another IP address (e.g. using VPN).  So far so good.

**Comment by UserUnknownFactor** [comment]
I really miss some kind of debugging info from `utils.py`, it helped me find that my requests were too large and timeout between them too low:

My take at debugging in  `utils.py`, don't really need to process error pages in the first place:
```python
def format_json(original):
    rtitle = None
    if original:
        # error pages always have a title
        rtitle = re.search(r'<title>(.+)<\/title>', original)
    if rtitle:
        raise 'Failed: %s' % rtitle.group(1)
    try:
        converted = json.loads(original)

**Comment by brada1703** [comment]
I am having the same problem. Unfortunately, another IP address (using VPN) is not working. :( Does anyone have another solution?
