### ISSUE TITLE
Improved Error Messaging when API rate limit exceeded

### ISSUE THREAD

**Issue by skanalytic** [ssut/py-googletrans#162]
I also hit this due to API limits. I think they should at least improve the error messaging here to make this clearer. 

"JSONDecodeError: Expecting value: line 1 column 1 (char 0)" (or anything in the callback trace) is not descriptive of the issue. It should be "LimitError: API Limit of <rate_limit> hit" or something.

_Originally posted by @skanalytic in https://github.com/ssut/py-googletrans/issues/144#issuecomment-614839998_

**Comment by skanalytic** [comment]
So has this been fixed?

**Comment by ssut** [comment]
Actually it's not if you are asking rate limits seemingly fixed, but I instead released a new version that returns `None` or `unexpected status code` error when it happens. The problem here is that we cannot know when a rate limit error is occurred, and how many times we should wait before making the api call again because this library is NOT an official lib that google supports. And contrary to the people saying, I don't believe responses without 20x is rate limit error because the standard HTTP response code of that is 429.
