### ISSUE TITLE
Abandoned ? What to do ?

### ISSUE THREAD

**Issue by 0mars** [ssut/py-googletrans#178]
Hi, It looks like there are no activities since Feb 8,

Is it possible that you add me to the contributers and I can take care of the package along with people's contributions ?

Thank you

**Comment by ssut** [comment]
I've been insanely busy and neglectful, and I know it's been effectively dead for quite some time now. So here I'm sorry for you guys waiting for pull requests to be merged and a new package to be released. Now I decided to give @0mars to have access to manage this repository in order to make the repo alive again. Thanks for your willingness to contribute for this project.

And for those people wanting to contribute, triage the project and start a roadmap, please feel free to contact me. I don't develop in python anymore, so I think I am not a right fit for the main maintainer for now so I hope someone would take over.

**Comment by terryyz** [comment]
Hi @ssut ,

I'll also be willing to continue working on this repository and manage it as well :-)

Cheers.

**Comment by ssut** [comment]
@terryyz I will contact you soon.

**Comment by ssut** [comment]
@terryyz Can you give me your email address please?

**Comment by terryyz** [comment]
Sure! My email address is `terryzhuo25@gmail.com`.

**Comment by shanginn** [comment]
sooo... is it still abandoned?
