### ISSUE TITLE
Is googletrans safe to use?

### ISSUE THREAD

**Issue by DesiKeki** [ssut/py-googletrans#266]
Hi Team,

First of all let me thank you for coming up with such a wonderful utility.

In the docs I read: **If you get HTTP 5xx error or errors like #6, it’s probably because Google has banned your client IP address.**

I understand that _it is not guaranteed that the library would work properly at all times_..., but if we use it on the risk of its discontinuity, is it also possible that Google may penalize the user in some way for using it?

Is using this library something like stealing from Google?

**Comment by ReihanHaekal** [comment]
Yes, Google can penalize us for using it. so why don't Google close this repo? Because there's a bunch of similar repos like this and even you can make one easily with numerous web scrape frameworks.

If you are developing an enterprise solution or something profitable consider using their own official translation APIs
