### ISSUE TITLE
Error issues with connection

### ISSUE THREAD

**Issue by TeCoEd** [ssut/py-googletrans#5]
Hi

I had been using the code for a while and then recently the same code will not translate -  states that the error is related to the Json request.  Have Google changed the API?
Thanks

**Comment by einverne** [comment]
Same problem.

**Comment by TeCoEd** [comment]
saw that the Google has withdrawn the API: https://github.com/terryyin/google-translate-python

**Comment by ssut** [comment]
I will check it out soon within a week.

**Comment by ssut** [comment]
I checked this issue in my dev environment and it seems it works, however, probably Google is now blocking some requests which are either unusual activity or uncharacteristic activity. So in that case, you can check the page that requires you to solve the captcha to continue; you guys need to use proxy server, or change your ip address in order to be able to continue.
