### ISSUE TITLE
How did you do reverse engineer to find the rule of generating token?

### ISSUE THREAD

**Issue by wzpfish** [ssut/py-googletrans#69]
Would you like to share some technique or experience?

**Comment by ssut** [comment]
You just have to see how web version of google translate works, with chrome inspector. Let's get into that: you can trace which scripts are called and with what params, when you typed something in the textarea. In order to explore, you can see what even listeners are registered to the object then you might see `keypress` or `keyup` event. After you found that, you will also see  `desktop_module_main.js:xxxx` and then click that. There would be a script that is messed up with obfuscator, so you can pretty print with the feature chrome inspector supports, then trace the behaviour with "Step over next function call (F10)", which also displays significant data.

So, this is all you need to do if you want to do it yourself. It's not so hard as it looks because the script itself cannot be concealed by the design of javascript, and the chrome inspector gives you some great hints called "Scope".
